### PR TITLE
Update quest.txt

### PR DESCRIPTION
**Pull request by thethingexe**
Added the new quest translations as well as some of the older missing translations. Also reformatted and corrected some things.

Can't actually check if A30-31 or B20 is working because I've already cleared them. I suspect there is something wrong in the description.

### CODE REVIEW

**Comment by thethingexe** [comment]
Thanks, I'm still pretty new to all the naval classifications.

**Comment by Zharay** [comment]
Not sure if this got merged in correctly. So I'll have to go over this manually, yay.

**Comment by Zharay** [comment]
Alright, now its in (on the master branch).

**Comment by thethingexe** [comment]
Yeah, I probably should have only put everything on the same branch instead of making two. But the other one is more complete.

Can probably just copy and paste over lines 57-102.

**Pull request closed without merging**
